" vim: nospell

if filereadable(expand("~/.vim/vimrc.functions")) | source ~/.vim/vimrc.functions | endif
if filereadable(expand("~/.vim/vimrc.config")) | source ~/.vim/vimrc.config | endif
if filereadable(expand("~/.vim/vimrc.maps")) | source ~/.vim/vimrc.maps | endif

" Add gruvbox9 colorscheme to runtime (is not available on github anymore)
set runtimepath^=~/.vim/unplugged/gruvbox9

" Load plugins
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

if filereadable(expand("~/.vim/vimrc.bundles"))
    source ~/.vim/vimrc.bundles
    if empty(glob('~/.vim/plugged'))
        autocmd VimEnter * PlugInstall --sync | source ~/.vim/vimrc.bundles.config | source ~/.vim/vimrc.maps | redraw
    else
        if filereadable(expand("~/.vim/vimrc.bundles.config")) | source ~/.vim/vimrc.bundles.config | endif
        if filereadable(expand("~/.vim/vimrc.bundles.maps")) | source ~/.vim/vimrc.bundles.maps | endif
    endif
endif

